version: '3'

services:
  app:
    build: .
    environment:
      - SERVER_PORT=8080
      - DB_HOST=db
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=move_easy_database
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:16
    environment:
      - POSTGRES_USER=mpa
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=move_easy_database
    ports:
      - "5432:5432"

