services:
  app:
    build:
        context: ..
        dockerfile: deploy/Dockerfile
    env_file: "../config/.env"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:16
    env_file: "../config/.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: docker.io/library/nginx:alpine
    ports:
      - "8081:8081"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/certs:/etc/nginx/certs
    depends_on:
      - app

volumes:
  postgres_data:
